### ISSUE TITLE
Suggest to fix problem with array of objects

### ISSUE THREAD

**Issue by tfiliano** [sindresorhus/lowercase-keys#2]
return JSON.parse(JSON.stringify(obj).replace(/"([\w]+)":/g,function($0,$1){return ('"'+$1.toLowerCase()+'":');}))

**Comment by sindresorhus** [comment]
Can you please elaborate?

**Comment by tfiliano** [comment]
When i have a json like:
[ { FOO: 'bar 1'}, { FOO: 'bar 2'} ] then I call your function the result is like: {'0': {foo: 'bar 1'}},{'1': {foo: 'bar 2'}}
With the code that I suggest, the results is like: [ { foo: 'bar 1'}, { foo: 'bar 2'} ]

'use strict';
module.exports = function (obj) {
  return JSON.parse(JSON.stringify(obj).replace(/"([\w]+)":/g,function($0,$1){return ('"'+$1.toLowerCase()+'":');}))
};

**Comment by sindresorhus** [comment]
The readme clearly says it accepts an object, not an array of objects. I'm not really interested in extending the use-case. You can easily map the array.

```js
[ { FOO: 'bar 1'}, { FOO: 'bar 2'} ].map(lowercaseKeys);
```
