### ISSUE TITLE
Deep option

### ISSUE THREAD

**Issue by skbolton** [sindresorhus/lowercase-keys#3]
Would you accept a PR that adds a recursive option to deeply lowercase the keys of an object?

**Comment by sindresorhus** [comment]
Sure, PR welcome. You could make use of https://github.com/sindresorhus/map-obj. The option should be named `{deep: true}`.

Inspiration: https://github.com/sindresorhus/camelcase-keys/blob/master/index.js

**Comment by rc1021** [comment]
#7 This is better. What do you think? @sindresorhus

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/lowercase-keys/commit/5966010461bf7629cc0e709de3c90148a2d4a2b5
